FROM quay.io/pypa/manylinux2014_x86_64
RUN yum install -y zip.x86_64
RUN yum install -y bzip2-devel.x86_64
RUN yum install -y ncurses-devel.x86_64
RUN yum install -y patchelf.x86_64
RUN yum install -y libXft-devel.x86_64
RUN yum install -y libXfont2-devel.x86_64
RUN yum install -y xorg-x11-fonts-Type1.noarch
RUN yum install -y editline-devel.x86_64
RUN yum install -y libedit-devel.x86_64
RUN yum install -y perl-IPC-Cmd
RUN yum install -y rh-perl530-perl-Time-Piece.x86_64