name: Build app root

on: [push, pull_request]

jobs:
  build_app_root:
    name: Build app root
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          cd docker
          bash build_docker_image.sh

      - name: Build root directory on docker
        run: |
          cd docker
          bash build_app_root.sh

      - uses: actions/upload-artifact@v4
        with:
          name: app_root
          path: ./docker/app_root*.*
